require('dotenv').config();
const { Client } = require('pg');

const setup = async () => {
    const client = new Client({
        connectionString: process.env.DATABASE_URL,
        ssl: {
            rejectUnauthorized: false
        }
    });

    try {
        await client.connect();
        console.log('✅ Connected to database successfully.');

        // 1. Create Tasks Table
        console.log('⏳ Creating tasks table if not exists...');
        const createTableQuery = `
            CREATE TABLE IF NOT EXISTS tasks (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                created_at TIMESTAMPTZ DEFAULT NOW(),
                title TEXT NOT NULL,
                status TEXT DEFAULT 'pending',
                owner_name TEXT,
                owner_open_id TEXT
            );
        `;
        await client.query(createTableQuery);
        console.log('✅ Table "tasks" is ready.');

        // 1.5 Enable RLS (Security Best Practice)
        console.log('🛡️ Enabling RLS...');
        await client.query('ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;');
        // Note: Without policies, RLS denies all access to 'anon' and 'authenticated' roles by default.
        // Your backend uses SUPABASE_SERVICE_KEY (service_role), so it will still have full access.
        console.log('✅ RLS enabled for table "tasks".');

        // 2. Check table contents
        console.log('⏳ Checking database contents...');
        const res = await client.query('SELECT * FROM tasks LIMIT 5');
        console.log(`📊 Found ${res.rowCount} tasks in database.`);
        if (res.rowCount > 0) {
            console.table(res.rows);
        } else {
            console.log('The "tasks" table is currently empty.');
        }

    } catch (err) {
        console.error('❌ Error initializing database:', err);
    } finally {
        await client.end();
    }
};

setup();
