-- Copy and paste this into Supabase SQL Editor

CREATE TABLE IF NOT EXISTS tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    status TEXT DEFAULT 'To Do',
    owner_name TEXT,
    owner_open_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Optional: Insert mock data
INSERT INTO tasks (title, status) 
VALUES 
    ('Thiết kế giao diện', 'To Do'),
    ('Xây dựng API', 'To Do'),
    ('Tích hợp Lark', 'To Do');
